baseURL = 'https://zvictorliu.github.io/operating_system/'
languageCode = 'en-us'
title = 'Operating System'
theme = 'book'
[params]
BookMenuBundle = '/menu'

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true